handler: lambdas/login/login.handler
name: login
role: !GetAtt CognitoAccessRole.Arn
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/login/login.js
environment:
  COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
  COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
  COGNITO_IDENTITY_POOL_ID: ${env:COGNITO_IDENTITY_POOL_ID}
events:
  - http:
      method: post
      path: login
      cors: true
