handler: lambdas/login/login.handler
name: login
timeout: 30
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/login/login.js
    - lambdas/login/helpers/**
environment:
  COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
  COGNITO_IDENTITY_POOL_ID: ${env:COGNITO_IDENTITY_POOL_ID}
events:
  - http:
      method: post
      path: login
      cors: true
      kaskadi-docs:
        description: This endpoint allows user to retrieve their authentication data given they provided a proper username and password.
        body:
          - key: method
            description: 'Defines the authentication provider. Valid values: `'Cognito'`, `'Google'`'
            default: 'Cognito'
          - key: token
            description: Access token to login. This is used only when logging in via Google.
          - key: Username
            description: Username used for logging in via AWS Cognito
          - key: Password
            description: Password associated with the given username for logging in via AWS Cognito
