handler: lambdas/refresh-session/refresh-session.handler
name: refresh-session
timeout: 30
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/refresh-session/refresh-session.js
    - lambdas/refresh-session/helpers/**
environment:
  COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
events:
  - http:
      method: post
      path: refresh
      cors: true
      kaskadi-docs:
        description: This endpoint allows user to refresh their access token in order to avoid having to log in again. This will work until their refresh token expires. **This currently does not support Google as an authentication provider.**
        body:
          - key: method
            description: "Defines the authentication provider. Valid values: `'Cognito'`, `'Google'`"
            default: 'Cognito'
          - key: refreshToken
            description: Refresh token provided when logging in. This applies only to session created via **Cognito**.
        examples:
          - request:
              body:
                refreshToken: cognito_refresh_token
            response:
              statusCode: 200
              headers:
                'Access-Control-Allow-Origin': '*'
              body:
                accessToken: cognito_access_token
                idToken: cognito_id_token
          - request:
              body:
                refreshToken: wrong_cognito_refresh_token
            response:
              statusCode: 401
              headers:
                'Access-Control-Allow-Origin': '*'
              body:
                message: Provided refresh token is incorrect.
