handler: lambdas/refresh-session/refresh-session.handler
name: refresh-session
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/refresh-session/refresh-session.js
    - lambdas/refresh-session/helpers/**
events:
  - http:
      method: post
      path: refresh
      cors: true
