name: build
on:
  pull_request:
    branches:
      - 'master'
      - 'dev'
    types: [opened, reopened, edited, synchronize]
    paths:
      - 'lambdas/**'
      - 'layer/**'
      - 'test/**'
      - 'package.json'
env:
  COGNITO_USER_POOL_ARN: ${{ secrets.COGNITO_USER_POOL_ARN }}
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  COGNITO_IDENTITY_POOL_ID: ${{ secrets.COGNITO_IDENTITY_POOL_ID }}
  CFD_KEY_PAIR_ID: ${{ secrets.CFD_KEY_PAIR_ID }}
  CFD_PRIVATE_KEY: ${{ secrets.CFD_PRIVATE_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Test
      run: npm test